export enum ErrMessage {
  INVALID_PARAM = 'INVALID_PARAM',
  ALREADY_EXISTS_EMAIL = 'ALREADY_EXISTS_EMAIL',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_CODE = 'INVALID_CODE',
  INVALID_FILE_ID = 'INVALID_FILE_ID',
}
