version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  was:
    build: .
    ports:
      - "30000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_CLIENT_ID: ${GMAIL_CLIENT_ID}
      GMAIL_CLIENT_SECERT: ${GMAIL_CLIENT_SECERT}
      GMAIL_REFRESH_TOKEN: ${GMAIL_REFRESH_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      redis:
        condition: service_started